spring:
  application.name: firstevent

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      enabled: true

      host: localhost
      port: 16379
      database: 0